### ISSUE TITLE
Disappearing text in settings

### ISSUE THREAD

**Issue by p0k33m0n** [tkashkin/Adwaita-for-Steam#107]
Disappearing text in settings when move mouse, it appear when clicking mouse on text.

Video included: https://megawrzuta.pl/download/756f1f6534a98b5aa3a8472d30532478.html

**Comment by tkashkin** [comment]
Is it on Windows? If so, that's a duplicate of #97.
I don't know why that happens, can try to figure out what's wrong in a few days.

**Comment by p0k33m0n** [comment]
Yes, this is Windows 10.

**Comment by p0k33m0n** [comment]
I send new video. This is interesting, that text start disappear when mouse is in different section. I didn't click any time, only move mouse.

https://megawrzuta.pl/download/47cc6633ed882cbbc459453f490424de.html

**Comment by zhouLife** [comment]
Me too win11_22H2

**Comment by Foldex** [comment]
> any progress with this?

![ill-tell-you](https://user-images.githubusercontent.com/47908676/229385936-96750cc1-ef10-4345-85fc-dafe9dfc794d.gif)

**Comment by p0k33m0n** [comment]
Thank you.
