### ISSUE TITLE
17/02 beta update broke full theme

### ISSUE THREAD

**Issue by alosarjos** [tkashkin/Adwaita-for-Steam#113]
Just notifying that with a full kind installation, the library is still looking like the default theme. I've seen some stuff has been broken on the Deck CSS themes, so probably Valve changes something :(

**Comment by rxfrxctxd** [comment]
Same here, the library and friend list look like the default theme, while e.g. the activity or store front pages look how they should.

**Comment by Foldex** [comment]
There's a few changes to classes here, but even classes that are the same and should be getting changed, aren't.

Manually inserting individual rules into the page works, so as far as I can tell it looks like for the beta client `webkit.css` is not being injected into these pages at all, and thus can't style anything.
 
Don't think anything can be done from our end. Might be best to open a report on [Valve's Issue Tracker](https://github.com/ValveSoftware/steam-for-linux/issues) and hope for the best.
In the meantime only workaround would be to opt-out of the beta.
