### ISSUE TITLE
Storage Manager does not handle game folder overload

### ISSUE THREAD

**Issue by RushingAlien** [tkashkin/Adwaita-for-Steam#117]
![gambar](https://user-images.githubusercontent.com/80886145/222934199-d2e46e37-c4dd-44fd-9f8b-9c310e3fa3fc.png)
Hello! Love your work.

I have found an issue on the Storage Manager menu, when there are more game library folders  than there are horizontal space to fit it in, there's no way to scroll over to view more, the original steam ui has arrows for this. We could do the same or perhaps a scroll bar instead ?

**Comment by RushingAlien** [comment]
That and if this happens, the close button will not be clickable as the other buttons are layered on top of it

**Comment by tkashkin** [comment]
Well, I've tried to keep it scrollable and move the buttons to the headerbar, but it wasn't as easy as I thought initially.
Then I thought something like "There's no way anyone will have more than 5 Steam library folders configured" and decided to keep it as is.

It should be possible to fix, but at this point I don't know if it's even worth trying if web-based parts of the skin stop working in the next Steam update (see #113).

**Comment by Foldex** [comment]
@RushingAlien 
The new UI merged Content Management into the settings menu, and as such the fancy headerbar display we were doing is no longer being used.
I don't think there would be, but can you confirm if there is still a usability issue with many Steam Library folders?

**Comment by tkashkin** [comment]
Valve has moved this into a separate Settings tab and replaced the tabs with a dropdown some time ago. This issue is no longer relevant.
