### ISSUE TITLE
Latest activity section can't be closed

### ISSUE THREAD

**Issue by KibaGasteiz** [tkashkin/Adwaita-for-Steam#129]
![Captura desde 2023-03-26 13-32-53](https://user-images.githubusercontent.com/44957566/227772961-31814e7a-09d5-4151-b04a-3e177f45beb8.png)

**Comment by Foldex** [comment]
![ss-2023-03-31_23:06:28](https://user-images.githubusercontent.com/47908676/229386357-0196e64a-bb93-4c73-a277-d27db041ed82.png)

Weird. 
The post game summary showing `X% of players have this achievement` has the close button for me.
Though yours lacks the `Post-Game Summary` header, so dunno if this is a similar-but-different dialog.

**Comment by KibaGasteiz** [comment]
Seems like they fixed it with todays release, thanks for the advice!
![Captura desde 2023-04-03 02-55-14](https://user-images.githubusercontent.com/44957566/229389386-def6822c-0141-4f23-b8f2-d421a1f889c9.png)
