### ISSUE TITLE
Restore window managment buttons

### ISSUE THREAD

**Issue by chikachit69** [tkashkin/Adwaita-for-Steam#136]
![screenshot](https://user-images.githubusercontent.com/129736109/229462076-9c12f022-1354-4871-9d23-1db1acb8a1ce.png)
I use the Pop Theme Skin version which is almost fits in perfectly with the rest of my Desktop Environmente but I'd like a way to Bring back the Minimize and Maximize buttons, similar to what Heroic and my other GTK apps have
![imageedit_3_8524159847](https://user-images.githubusercontent.com/129736109/229464062-148f2350-e7bb-41c8-826d-3b7c51eb39ff.png)

**Comment by Foldex** [comment]
This is already an option.

CLI installer:
`python install.py -p windowcontrols/right-all`

GUI installer:
![image](https://user-images.githubusercontent.com/47908676/229646372-3f22119b-c5ea-476e-ba13-614bb4822343.png)
