### ISSUE TITLE
Please make the game icons in the list square with rounded corners instead of round. 

### ISSUE THREAD

**Issue by Blisterexe** [tkashkin/Adwaita-for-Steam#142]
i ask for this because many icons _(have a nice death, doom eternal, redmatch 2, and ultrakill among others)_ look weird as they are intended for a square format. I think changing them to be square with rounded corners would still look very good, while making the icons look right, i would also very much appreciate removing the grey background behind the icon so that icons with transparent elements look better (if possible)
attached is a picture of what i mean:
![Screenshot from 2023-04-25 21-52-18](https://user-images.githubusercontent.com/128065612/234445880-e2466bd8-fb60-49b3-a90c-b131af183107.png)
![Screenshot from 2023-04-26 10-22-54](https://user-images.githubusercontent.com/128065612/234606294-891ed6f5-3791-4e46-9133-06087568206a.png)

**Comment by Foldex** [comment]
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/0aa6228e-d396-42b1-9c91-57f516c4bdcc)

Although, not sure what you meant by transparency. All these sidebar images seem to be jpgs, which doesn't support that.
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/fcc02d34-be16-41b0-a8ea-ee00bb48d478)

**Comment by Blisterexe** [comment]
awesome! Thankj you so much for implementing my suggestion, and to clarify, what i meant by "the grey background behind the icon" is the fact that the grey behind the transparent parts of icons is different from the rest of the background is different from the rest of the backgound.
![Screenshot from 2023-06-18 21-16-57](https://github.com/tkashkin/Adwaita-for-Steam/assets/128065612/98a55d0a-0984-489a-ab86-7fba9f6b98dc)
