### ISSUE TITLE
Beta: Interface Changes

### ISSUE THREAD

**Issue by Foldex** [tkashkin/Adwaita-for-Steam#144]
[Latest Beta](https://store.steampowered.com/news/app/593110/view/3686801719529689367) dropped, bringing with it a number of changes.
Unfortunately has some loss of functionality associated on our end, seems Valve likes making it hard on skin makers.
Regardless, seems like supporting this will involve some significant changes.

- VGUI is kill, along with the ability to select skins at all. Entirely Web based UI now.
- Library skinning still works, so at least directly patching steam files is still an option.
- Naturally without skin support, injecting `webkit.css` from one is no longer an option. This breaks anything still using that (Login, Friends, etc), and those will have to be moved into client patches.
- Unknown if there's a way to theme pages that were simply accessing steam's website (Store, Profile, etc) anymore, since we probably can't patch those and `webkit.css` will no longer be injected there.
- New Settings, which thankfully seems to be unified into a `pagedsettings_PagedSettings` dialog, so it at least inherits that existing styling.
- New Web Based In-Game Overlay.
- New Notifications.
- New Screenshot Manager.
- As per #139, Game properties has changed slightly.

**Comment by Eschguy** [comment]
Just installed v38 and yeah....it's rough. Seems deleting everything in .steam/skins doesn't revert all changes, either.

**Comment by tkashkin** [comment]
@Eschguy This skin patches a few css files outside of the `skins` directory since #120.
You'll have to reset these patches for now if you want to stay on the client beta branch.

Use one of the following methods:

* Rerun the installer script with `--web-theme none` or select `Web theme: None` in AdwSteamGtk and reinstall the skin.
* Remove `clientui/css/friends.css`, `clientui/friends.custom.css`, `steamui/css/library.css`, `steamui/libraryroot.custom.css`.
* Just remove the whole `clientui` and `steamui` directories and start Steam to let it extract them again.
* Do something else to force Steam to overwrite patched files, maybe switch to the stable branch and back to beta.

**Comment by Eschguy** [comment]
> @Eschguy This skin patches a few css files outside of the `skins` directory since #120.

Ahh I missed that release note, makes sense.

**Comment by Foldex** [comment]
Opened a PR to add uninstall info to the readme.

I also have an initial beta branch [here](https://github.com/Foldex/Adwaita-for-Steam/tree/beta). 
Login is fixed, Chat is fixed, Context Menus fixed, and the Header/Footer Bars at least aren't garish blue anymore.
But besides that, expect lots of bugs, this is basically the bare minimum of fixing up. 

Unfortunately this comes at a bad time, as I'm not going to have much time to polish this further in the immediate future. So there's the heads up if anyone wants to fix this up more.

You can find information about inspecting Steam's classes [here](https://github.com/tkashkin/Adwaita-for-Steam/tree/master/extras/web)
One note is that since the update the `F12` shortcut is a bit finnicky, I've had better luck right clicking a text box and using `Inspect Element`

![image](https://user-images.githubusercontent.com/47908676/235279573-59e12636-25db-4d0c-8d33-8ce1d7fa5de0.png)


If you're still interested in using the beta, you can tide yourself over via:
```sh
git clone https://github.com/Foldex/Adwaita-for-Steam.git -b beta
cd Adwaita-for-Steam
./install.py
```

The rest is still going to take some work, but at least this is much less in your face broken.

We still have a loss of customization since we would no longer have control over the underlying layout of the headerbars like with VGUI. This means stuff like adding new buttons/links is pretty much out of the question, since to my knowledge there's no easy way to patch the underlying html. Being stuck with css, we can only style elements, not add them.

On the plus side, the elimination of VGUI does also effectively clean up some of the longer standing VGUI issues:
#37 #97 #105 #107 #108 , granted some of those will have web theme equivalents.

**Comment by Foldex** [comment]
Had time to update the beta branch a little:

![image](https://user-images.githubusercontent.com/47908676/236341316-533b7ad5-d157-4ff8-bb5f-63a0e2a6de13.png)

Forward/Back Arrows had to be hidden since I couldn't find a good place for them.

Still needs work:
- Overlay (Skinning seems to work, but dunno how to get the inspector working here)
- Notifications
- Settings / Game Properties
- Add Non-Steam Game
- Product Activation
- Recent Players
- Game Servers
- Screenshots
- Update News
- About Steam
- System Info
- Probably more stuff

**Comment by IceDBorn** [comment]
@Foldex It looks perfect, good job!

**Comment by Eschguy** [comment]
Looks great! Wondering if there's a way to do some kind of auto-sizing blank space for the top bar. It gets a bit cramped at my default window size for Steam. 
![Screenshot from 2023-05-05 07-15-17](https://user-images.githubusercontent.com/8880292/236455499-e36ac471-9bf7-460b-a644-ea26dbae90d2.png)

**Comment by Foldex** [comment]
> Looks great! Wondering if there's a way to do some kind of auto-sizing blank space for the top bar. It gets a bit cramped at my default window size for Steam.

Unfortunately it's a case of having to resort to hackery to get it like this. The headerbar isn't actually a single row, it's two different rows being overlayed on top of each other. The actual layout (which we no longer control) looks something like this:

![image](https://user-images.githubusercontent.com/47908676/236516066-acb6203e-6df8-4cde-ac15-fb713d377997.png)

So the center and sides aren't really "aware" of each other's personal space. I could maybe do some squeezing of elements at smaller window sizes (the profile button being a good candidate), but technically there is nothing preventing overlap if it does occur.

The alternative is to keep the dual row layout which would look awful and really doesn't fit adwaita at all.

**Comment by Caliel666** [comment]
> The alternative is to keep the dual row layout which would look awful and really doesn't fit adwaita at all.

it indeed does not fit the general adwaita style, but if you have to go with that, you can probably make it look like Epiphany tabs, could at least be made into a option

**Comment by Foldex** [comment]
[screen.webm](https://user-images.githubusercontent.com/47908676/236641756-bec205b0-f87c-480d-bed7-c0d1d7106fa6.webm)


- Now adjusts based on window size to try to prevent overlap. Certain combinations of optional Web Extras at the very smallest of window sizes will have slight overlap/look bad, but don't think it's avoidable. 
- Navigation icons are back.
- Window control web extras e.g. `left` `left-all` `right-all` should be working now.
- Added Web Extras for hiding the Bottom Bar and Big Picture Button.
- Added Web Extra for showing Forward/Back arrows, if you don't mind the extra clutter.
