### ISSUE TITLE
Import yaru icons

### ISSUE THREAD

**Issue by Jupi007** [tkashkin/Adwaita-for-Steam#148]
Hi,
I maintain a fork of your project, patched with real yaru icons and some minor adjustments: https://github.com/ubuntu/yaru-for-steam

I was wondering if you'd be interested in adding our icons to your repository.
This would make your yaru theme look more yaru-ish and thus more native to ubuntu.

I would like to create a PR, so please let me know if it's ok with you :)

**Comment by Jupi007** [comment]
Thanks for your reply !

I don't have that much time, so if you say it could be useless in a couple of week, I would prefer to see where it is going to go before working on this.
I subscribed to the beta UI issue you linked, so I can follow the discussion.

If it is still possible in the future to use custom icons, I would be very happy to contribute :)

**Comment by Foldex** [comment]
Just as a heads up:

This is definitely doable in the new UI. It becomes a bit cleaner to do, even.

We're no longer dealing with pregenerated tga assets and can just plop SVGs in where we need them. 
Furthermore, themes can simply override the base icon variables should they want to.

Right now we are only defining Navigation Menu icons (as they didn't exist in the new UI), but it's technically possible to extend this further.

You can see the current icon definitions [here](https://github.com/Foldex/Adwaita-for-Steam/blob/19c43290d945278d0025150ba628e6b00439690c/web/base/_root.css#L167) 

Yaru theme [here](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/colorthemes/yaru/yaru.theme)

Only thing to note is that while the original definitions are not, any icon overrides in the theme should be base64 encoded.

```sh
echo "url('data:image/svg+xml;base64,"$(openssl base64 < icon.svg)"');"
```

So to override the library icon you would simply add an entry to the theme:
```ini
[icons]
library_icon = url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBoZWln aHQ9IjE2cHgiIHZpZXdCb3g9IjAgMCAxNiAxNiIgd2lkdGg9IjE2cHgiIHhtbG5z PSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8ZyBmaWxsPSIjMmUz NDM2Ij4KICAgICAgICA8cGF0aCBkPSJtIDUgMTIgdiAxIGggMC4wMDc4MTIgYyAt MC4wMDM5MDYgMC4yNjU2MjUgMC4xMDE1NjMgMC41MTk1MzEgMC4yODUxNTcgMC43 MDcwMzEgbCAyIDIgYyAwLjM5MDYyNSAwLjM5MDYyNSAxLjAyMzQzNyAwLjM5MDYy NSAxLjQxNDA2MiAwIGwgMiAtMiBjIDAuMTgzNTk0IC0wLjE4NzUgMC4yODkwNjMg LTAuNDQxNDA2IDAuMjg5MDYzIC0wLjcwNzAzMSBoIDAuMDAzOTA2IHYgLTEgeiBt IDAgMCIvPgogICAgICAgIDxwYXRoIGQ9Im0gOCAtMC4wMDc4MTI1IGwgLTUgMy4x NDA2MjQ1IHYgNC43MTQ4NDQgbCA1IDMuMTQ0NTMyIGwgNSAtMy4xNDQ1MzIgdiAt NC43MTQ4NDQgeiBtIDAgNi4wMDAwMDA1IGwgLTMuNjQ0NTMxIC0yLjE3NTc4MiBs IDMuNjQ0NTMxIC0yLjI5Mjk2OCBsIDMuNjQ0NTMxIDIuMjkyOTY4IHogbSAwIDAi Lz4KICAgIDwvZz4KPC9zdmc+Cg==')
```

Before:
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/7b18e606-2408-4358-b9c5-685aaf9cea43)

After:
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/86f9048e-6e02-4821-a510-099df52a0fd8)

**Comment by Jupi007** [comment]
Sorry for the delay.

Thanks a lot @Foldex for the detailed reply!

As soon as I find the time, I'll take a look at override the icons and then do a PR for this repo :)
