### ISSUE TITLE
Installer Frontend?

### ISSUE THREAD

**Issue by Foldex** [tkashkin/Adwaita-for-Steam#15]
[2022-08-28_16-44-48.webm](https://user-images.githubusercontent.com/47908676/187094793-51425138-682f-46b7-bac8-07bd7f488f3d.webm)

Just a quick (and non functional) mockup for a python+libadwaita installer frontend, would there be any interest in me building it out further?
Would allow for an easy flatpak distribution method, and could potentially be built out to add in a color editing interface.

**Comment by tkashkin** [comment]
I thought about making something like this.

Not sure if it makes sense to distribute it as a flatpak or it could just be a script like the current installer.
If it is a flatpak it should probably be in a separate repo and it should download the latest skin version to avoid having to publish a new installer flatpak when the skin is updated.

> could potentially be built out to add in a color editing interface.

This case somewhat overlaps with [Gradience](https://github.com/GradienceTeam/Gradience) and its devs [consider making a plugin for this skin](https://github.com/GradienceTeam/Gradience/issues/120).
Maybe there's no need for a separate installer app at all and it can also be a part of this plugin (though it would mean you have to install Gradience to access the installer GUI even if you don't want recoloring).

**Comment by Foldex** [comment]
> Not sure if it makes sense to distribute it as a flatpak or it could just be a script like the current installer.
>If it is a flatpak it should probably be in a separate repo and it should download the latest skin version to avoid having to publish a new installer flatpak when the skin is updated.

I'm partial to a flatpak over a script myself, but I guess if it went that route then a separate repo would be fine. 

> This case somewhat overlaps with [Gradience](https://github.com/GradienceTeam/Gradience)

Neato, didn't know about this project. :+1: 

>  and its devs [consider making a plugin for this skin](https://github.com/GradienceTeam/Gradience/issues/120). Maybe there's no need for a separate installer app at all and it can also be a part of this plugin (though it would mean you have to install Gradience to access the installer GUI even if you don't want recoloring).

In that case I'm fine with leaving the heavy lifting to Gradience, though I could still see some use in simpler app being around. Gnome apps are allegedly all about removing features after all.

In any case: I'm not married to the idea or anything, was mostly using it as an excuse to familiarize myself with libadwaita widgets and figured I'd run it by you. If I do continue it would be it's own thing though, so I'll close this as such.

**Comment by 0xMRTT** [comment]
Plugin support is coming very soon. Will create a plugin for this when ready 😉
