### ISSUE TITLE
[Feature Request] Allow using custom/system font?

### ISSUE THREAD

**Issue by qwertychouskie** [tkashkin/Adwaita-for-Steam#163]
It would be nice for Steam to use the same font as the rest of my system.

**Comment by Foldex** [comment]
Already possible.
`-we` accepts any arbitrary css file you want to throw at it, and is capable of overriding our [css variables](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/web/base/_root.css).

The usual warnings apply: Changing the font can wind up causing visual bugs, your favorite font is not officially supported, yadda yadda.

`./install.py -we ~/path/to/wherever/custom.css`

### custom.css
```css
:root
{
	--basefont: "Font Name"
}
```

<details><summary>Perfection</summary>
<p>

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/1607653f-bf68-4641-b07e-e1ac2a09c5dc)

</p>
</details>

**Comment by qwertychouskie** [comment]
Perfection!

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/13989090/42f536b4-0cb1-4071-97ce-e9365f7542dd)

(Comic Sans gets way more hate than it deserves.  I set it as a meme originally but now I've been using it for like a year unironically.)

**Comment by Foldex** [comment]
A casualty of it coming preinstalled and getting used in one too many bad applications.

Since we're good here, Mind closing the issue?

**Comment by qwertychouskie** [comment]
It's probably be good to document this in https://github.com/tkashkin/Adwaita-for-Steam/blob/master/README.md before closing this issue.
