### ISSUE TITLE
Add option to hide VR Mode button

### ISSUE THREAD

**Issue by Commenter25** [tkashkin/Adwaita-for-Steam#168]
Similar to the Big Picture button, there is a VR button which always displays. This used to only appear when a headset was actively plugged in, but this seems to no longer be the case. Since there is already an option to hide the Big Picture button, it makes sense to have an option to hide this too.

![Screenshot displaying the VR mode button in the top right of the window](https://github.com/tkashkin/Adwaita-for-Steam/assets/35016761/f0b9a4bb-b000-4371-a3db-f94410cf403c)

**Comment by Foldex** [comment]
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/151cb0c0-e2f4-4f7b-98a2-3f209195b0e7)

Can't seem to reproduce, granted I don't have a VR headset to begin with.
This sounds more like a steam client bug to me, with the button display somehow remaining enabled when it shouldn't.

As for an option to disable it, I'm against it. It'd be one thing if it displayed for every user regardless of VR support, but that doesn't seem to be the case. It wouldn't make much sense to hide a button that only shows up for VR users, which presumably has useful functionality for them. Even accounting for this bug, it would be very inconvenient that anytime you actually do want access to the button, you'd have to repatch, restart steam, and then repatch/restart again to disable it after you're done with it.

**Comment by Commenter25** [comment]
Perhaps if you install and launch SteamVR, it will appear?

I disagree about that. Big Picture can still be opened by other methods without the button for it. Likewise, VR Mode can be activated without that button. All it does is launch SteamVR, which is also an app in the library. And there's also a button in the same menus that let you launch Big Picture. With the rarity I open VR, I would rather hide that button for UI cleanliness, and just go to SteamVR in my library if I need to. Technically I wouldn't even need to do that, as launching a VR game automatically opens SteamVR.

**Comment by Foldex** [comment]
>Perhaps if you install and launch SteamVR, it will appear?

Still nope. :shrug:

>Likewise, VR Mode can be activated without that button. All it does is launch SteamVR, which is also an app in the library. And there's also a button in the same menus that let you launch Big Picture. With the rarity I open VR, I would rather hide that button for UI cleanliness, and just go to SteamVR in my library if I need to. Technically I wouldn't even need to do that, as launching a VR game automatically opens SteamVR.

I presumed it would've had exclusive functionality, but if that's the case then I guess my fears were unfounded.

```sh
git clone https://github.com/Foldex/Adwaita-for-Steam.git -b hide_vr_button
./install.py -we topbar/hide_vr
```

If you can test to make this this works, I'll open the PR.

**Comment by Commenter25** [comment]
Can confirm that it works! Thank you!
