### ISSUE TITLE
Simplify installation variants

### ISSUE THREAD

**Issue by tkashkin** [tkashkin/Adwaita-for-Steam#177]
We already patch client CSS anyway, there's no point in keeping `base` and `full` variants separate.
And there's no VGUI part anymore, so `web` distinction doesn't make a lot of sense either.

**Comment by Foldex** [comment]
`base` has kind of fallen to the wayside, and I've thought of removing it as well.
`full` has largely stabilized, so `base` really is just an incomplete, worse version at this point.

Fine with renaming `web`  as well.
