### ISSUE TITLE
Some global styles affect Big Picture UI

### ISSUE THREAD

**Issue by tkashkin** [tkashkin/Adwaita-for-Steam#190]
<details><summary>Text fields</summary>
<p>

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/9928c586-2fa3-47cd-a6d5-0d2e0fd29c9a)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/0766427c-4b80-4754-a4f3-6c6a47367fd4)

</p>
</details>

<details><summary>Dialogs - breaks controller focus indication for dialog buttons</summary>
<p>

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/0f5aa882-ed5a-436a-ade0-f47fc5d9b5a1)

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/3ff3dba7-fd2d-44ee-a5a0-7a0207e7be8e)

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/31a863f9-6397-44d4-88c4-7cf4f213ab42)

</p>
</details>

**Comment by KyleGospo** [comment]
This also affects Gamemode on the Steam Deck

**Comment by KyleGospo** [comment]
Fixed via loading with CSS loader in latest builds.

**Comment by LittleFreak** [comment]
> This also affects Gamemode on the Steam Deck
I installed Adwaita in Desktop mode and use DeckyPlugins/CSS Loader in gaming mode. Therefor I have the same Issue, that the Dialogues in GM share the Adwaita theme. 
> Fixed via loading with CSS loader in latest builds.
You've installed Adwaita in Gaming Mode directly with CSSLoader? How? Haven't seen it anywhere.

**Comment by KyleGospo** [comment]
> > This also affects Gamemode on the Steam Deck
> 
> I installed Adwaita in Desktop mode and use DeckyPlugins/CSS Loader in gaming mode. Therefor I have the same Issue, that the Dialogues in GM share the Adwaita theme. 
> > Fixed via loading with CSS loader in latest builds.
> 
> You've installed Adwaita in Gaming Mode directly with CSSLoader? How? Haven't seen it anywhere.
> 

Latest commits add the needed config for it. Uninstall the theme however you've already installed it, then git clone it into ~/homebrew/themes and select it with CSS Loader. It'll now only load on the desktop. Just make sure you enabled standalone mods in css loader settings.
