### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by orowith2os** [tkashkin/Adwaita-for-Steam#2]
I'm currently looking at trying to do something similar to this for the Steam client, although using a different style. I'm planning to base it off of this. 
Adding a license would specify the terms of which someone can use this work, I recommend MIT for one of the most permissive ones, although something like the BSD 2/3-Clause would work as well. I also recommend looking into the licenses yourself to make the choice.

**Comment by TheEvilSkeleton** [comment]
I suggest using a creative work license like Creative Commons, since it's CSS.

**Comment by orowith2os** [comment]
Skel makes a good point. If you choose to use the CC instead, the [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) has similar terms, although it requires credit. Again, look into the available choices, and choose what you think is best.

**Comment by tkashkin** [comment]
Well, I have no idea what to pick. I guess I'll wait for more suggestions and then try to decide.

Some additional considerations and questions that I have absolutely no idea how to answer:
* Does the license have to be compatible with libadwaita's license ([LGPL-2.1+](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/COPYING)), is it a derivative work if I recreate libadwaita's styling for a different UI framework?
* Does it need to be compatible with Steam default skin somehow if it even has a license?
* Which licenses are used by other popular Steam skins or other similar projects?

**Comment by orowith2os** [comment]
Derivative works only apply if they use any of the code from it, so writing some code to look and work functionally the same without using any code from the original project should be fine to be considered separate, and not a derivative work. I'm not a lawyer, so don't quote me on that, but I'm pretty sure. I'll see if I can find some other steam skin licenses.

**Comment by FeyXieXzf** [comment]
> Does the license have to be compatible with libadwaita's license ([LGPL-2.1+](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/COPYING)), is it a derivative work if I recreate libadwaita's styling for a different UI framework?
No and no, because this skin doesn't contain anything from libadwaita.

> Does it need to be compatible with Steam default skin somehow if it even has a license?
Idk on this, but I guess no.

**Comment by DaniD3v** [comment]
this can be closed there's an MIT license now

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tkashkin/Adwaita-for-Steam/issues/2#issuecomment-2019093609

Indeed - https://github.com/tkashkin/Adwaita-for-Steam/blob/90f743310edf52a0b53bb70c2ebcf702b0ed771a/LICENSE#L1-L21:~:text=21-,MIT%20License,-Copyright%20(c)%202022.
