### ISSUE TITLE
Web pages overlap bottom left rounded corner

### ISSUE THREAD

**Issue by AlexRay21** [tkashkin/Adwaita-for-Steam#200]
https://drive.google.com/file/d/14FaCis41uisBSp_goBk2lH4BZfGyt75U/view?usp=share_link

**Comment by nanopone** [comment]
the actual image for people who dont want to click on a google drive link:
![Снимок экрана от 2023-08-15 16-20-29](https://github.com/tkashkin/Adwaita-for-Steam/assets/49787675/9994fd03-0c78-49f2-8418-5743d6b89d7e)

**Comment by tkashkin** [comment]
Somewhat fixed in v2.0 by not trying to round window corners anymore, because we can't do that reliably with all Steam windows.
