### ISSUE TITLE
catppuccin-mocha not working on windows

### ISSUE THREAD

**Issue by ohitstom** [tkashkin/Adwaita-for-Steam#202]
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/22730962/ad3acea2-afba-41b0-b9a2-8109d0cfca01)
followed the instructions, ran the windows install bat, chose mocha, no mocha.
steam is installed on the D drive not the C drive

**Comment by tkashkin** [comment]
Try running the installer directly.

```
python3 .\install.py -c catppuccin-mocha
```

It should print an error if something goes wrong, but you can't see its output if you use the bat script.

**Comment by Andryshik345** [comment]
I also started to have this issue this morning, tried both batch and calling python script directly,
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/24612088/709d545a-090a-40ff-8192-82b6eb06d859)

Script also fails to uninstall it completely, leaving `library.original.css`, so I have to remove it or replace with patched `library.css` manually if I want to install it next time (yes I'm aware that it's not necessary to uninstall it every time, just saying).

Steam installed at default location.
