### ISSUE TITLE
Doesn't work with Steam flatpak

### ISSUE THREAD

**Issue by K0-RR** [tkashkin/Adwaita-for-Steam#216]
I installed Steam from the flathub, and it doesn't work with it.

**Comment by Vovkiv** [comment]
Try install it using: https://github.com/Foldex/AdwSteamGtk

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tkashkin/Adwaita-for-Steam/issues/216#issue-1944096344

@K0-RR, that installer is mentioned in https://github.com/tkashkin/Adwaita-for-Steam/blob/7c1454ec946a6ebb3f0221404800b4e4c5d935ed/README.md#with-graphical-installer. Always good to read the documentation.
