### ISSUE TITLE
Text overlapping past title bar (Visual Bug)

### ISSUE THREAD

**Issue by syns** [tkashkin/Adwaita-for-Steam#217]
I have an account alert and the text for account alerts expands past the title bar. It gets cut off at the top of the page and overlaps onto the page below.
![gif](https://github.com/tkashkin/Adwaita-for-Steam/assets/44479102/0a401878-a357-409b-8f7c-a787ac1da61d)
I am on Adwaita version 1.13 as of writing this and all advanced configuration options I've tried have not changed the broken text. 
Love the theme <3

**Comment by tkashkin** [comment]
It's hard to fix without me having an account alert on my account. I'll need class names or full HTML of that button.

Can you [open the inpector](https://github.com/tkashkin/Adwaita-for-Steam/tree/master/adwaita#inspecting-steam), find the button itself or the whole `div.titlebarcontrols_TitleBarControls_`, and copy the element here?

It should look like this:
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/345a0139-8ada-4d48-ad17-d7e5eccc9dc7)
