### ISSUE TITLE
Change the restore window icon to be more Adwaita-like

### ISSUE THREAD

**Issue by ArtyIF** [tkashkin/Adwaita-for-Steam#221]
In Adwaita, the restore window icon (the de-maximize one) is a smaller square, but in this theme, it's more Windows-like.

GNOME's Text Editor:
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/8017858/4f3bc75d-2d83-4376-a901-0d27b7880ca6)

Adwaita for Steam:
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/8017858/e4cc64cc-57c9-485b-8933-bc0f51efd038)

**Comment by tkashkin** [comment]
Fixed in v2.0.
