### ISSUE TITLE
Drop-down menus render with black corners

### ISSUE THREAD

**Issue by qwertychouskie** [tkashkin/Adwaita-for-Steam#222]
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/13989090/91f0ccab-7f7b-42d5-bdba-540af8c89c4d)

I do have the Rounded Window Corners extension installed for what it's worth.

I suspect the simplest option is to disable rounded corners for the drop-down menus.  I know I can disable all rounded corners, but I don't want to disable them all, just these buggy menus.

**Comment by PussInScreen** [comment]
I can confirm this isn't something you're encountering on your own.

**Comment by tkashkin** [comment]
Fixed in v2.0.
