### ISSUE TITLE
New Steam Beta broke the CSS injection

### ISSUE THREAD

**Issue by IceDBorn** [tkashkin/Adwaita-for-Steam#229]
Valve updated the Steam beta client to use a newer version of chromium. That might have broken the way you inject CSS to the Steam client.

**Comment by tkashkin** [comment]
It works as before, at least on the [`next`](https://github.com/tkashkin/Adwaita-for-Steam/tree/next) branch. A couple of small issues in the new beta are already fixed there.

`master` branch should also continue to work if classes have not changed.

**Comment by IceDBorn** [comment]
I'm using the latest release.

**Comment by tkashkin** [comment]
The latest release still works fine for me on the Steam beta, you just need to reinstall the skin.

There are a couple of bugs which are already fixed in `next`. The fixes are simple enough, I'll probably backport them to `master`.

**Comment by tkashkin** [comment]
Try [v1.16](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v1.16) and let me know if it still doesn't work.

**Comment by DisasterIncarnate** [comment]
Uninstalled/Reinstalled and the skin doesnt appear after recent update(s), theres not even a skin option in Steam's New UI - Settings/Interface to pick.
