### ISSUE TITLE
Headerbar drop down menu styling

### ISSUE THREAD

**Issue by Doomsdayrs** [tkashkin/Adwaita-for-Steam#23]
Is there a way to get this styled?

![image](https://user-images.githubusercontent.com/38189170/192623727-a4b61ccb-cb7d-42f3-8750-cbd650ca4d91.png)

**Comment by tkashkin** [comment]
There is no way to increase the menu item height and there is no way to make the menu corners rounded.
Otherwise it's already close to how Adwaita menus look, not sure what else can be done here.

**Comment by Doomsdayrs** [comment]
Are we able to open up an issue with valve for this?
