### ISSUE TITLE
Design mismatches

### ISSUE THREAD

**Issue by cmkohnen** [tkashkin/Adwaita-for-Steam#232]
I've stumbled across a few inconsistencies in contrast to default Libadwaita behaviour:
- When deselected the knob of switches should have the colour `#d2d2d2` instead of `#ffffff` (Game properties)
- When hovering over a switch in deselected state, the colour should be `#636363` instead of `#4e4e4e` (Game properties)
- The container should have the colour `#363636` instead of `#3a3a3a` (Game properties)
- On hover the container should have the colour `#3c3c3c` instead of `#454545` (Game properties)
- The hover effect in settings doesn't match:
![Bildschirmfoto vom 2024-02-07 19-59-02](https://github.com/tkashkin/Adwaita-for-Steam/assets/59118042/deb6fdd8-6524-4e80-ae26-2313da5c3a3f)
- In general the mouse pointer should't change to the hand when hovering over clickable buttons, dropdowns, etc.
- Dropdowns in Game properties should activate when clicking the container. The container should also receive a hover effect.
- This should be connected:
![Bildschirmfoto vom 2024-02-07 20-18-21](https://github.com/tkashkin/Adwaita-for-Steam/assets/59118042/63d0a0a6-8124-48b7-bc8d-14e015514142)
- The Headerbar is misaligned and for some reason hoverable:
![Bildschirmfoto vom 2024-02-07 20-19-00](https://github.com/tkashkin/Adwaita-for-Steam/assets/59118042/15f566db-bef2-4c2d-ac73-f6f74c8d7498)
- (probably) all popout windows are missing a frame

**Comment by tkashkin** [comment]
Should mostly be fixed in v2.0.
