### ISSUE TITLE
Can't Undo Theme

### ISSUE THREAD

**Issue by ThisByzantineConduit** [tkashkin/Adwaita-for-Steam#233]
The theme actually altered the appearance of windows in Gaming 
Mode on SteamOS and not just desktop mode client. I uninstalled this app and removed all data and settings and I can't get it to go back to stock appearance. Maybe I'm being dumb and missing something though but please let me know!

**Comment by ThisByzantineConduit** [comment]
For anyone who has this issue, I found a solution. Go to .steam (hidden folder in home/deck) and "steamui" folder and delete the "adwaita" folder. That fixed it!

**Comment by dxcvvxd** [comment]
`./install.py -u`?

**Comment by PussInScreen** [comment]
I'm certain the other two methods work as well but to add more fuel to the fire there's uninstall in the AdwSteamGtk Flatpak too;
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/19553807/252d035c-963b-4bf0-a807-f02d8dc4906e)
