### ISSUE TITLE
Broken round corners

### ISSUE THREAD

**Issue by pchmykh** [tkashkin/Adwaita-for-Steam#234]
With AdwSteamGtk 0.6.9 round corners are broken, please find screenshot in attachment.
![Screenshot from 2024-03-02 10-07-47](https://github.com/tkashkin/Adwaita-for-Steam/assets/125208381/4d5fc37a-49df-491d-abfc-dc9705241076)

**Comment by GittyMac** [comment]
I think it's a limitation with the Steam app not being a full GTK window, as the README recommends using some GNOME modifications to fully round the window.

> Rounded corners: Not all elements can be rounded, use [Rounded Window Corners extension](https://github.com/yilozt/rounded-window-corners) or [mutter-rounded](https://github.com/yilozt/mutter-rounded) on GNOME.

**Comment by tkashkin** [comment]
Somewhat fixed in v2.0 by not trying to round window corners anymore, because we can't do that reliably with all Steam windows.
