### ISSUE TITLE
Not a bug, but a future fix

### ISSUE THREAD

**Issue by ShadowMonster99** [tkashkin/Adwaita-for-Steam#236]
I develop and maintain theming for steam and I remembered this project and just wanted to drop this repository as the Steam Beta update changes all the class names and you would have to rewrite your theme without using this. 

- https://github.com/SteamClientHomebrew/ClassMapper
create an issue if something arises.

Cheers,
Shadow

**Comment by tkashkin** [comment]
Thanks. The [`next`](https://github.com/tkashkin/Adwaita-for-Steam/tree/next) branch is already updated using a class map from https://api.deckthemes.com/beta.json, but this may be useful in the future if Valve decides to change classnames again.

**Comment by ShadowMonster99** [comment]
perfect! just wanted to make sure this theme wasn't just left to rot.

Have a good one.
