### ISSUE TITLE
Install Games is implemented as a modal and can't scroll/select okay when installing many games.

### ISSUE THREAD

**Issue by sockusminimus** [tkashkin/Adwaita-for-Steam#239]
The Install Games dialog is implemented as a modal.  As a result, when installing too many games (e.g. enough to make the modal taller than the underlying steam window) there is no way to select "Install" for the selection.
![Screenshot from 2024-04-28 18-27-47](https://github.com/tkashkin/Adwaita-for-Steam/assets/83981169/1f26eded-9f63-4344-9117-c071670ad3f8)

**Comment by tkashkin** [comment]
The latest skin version reverts dialog styles to defaults for now.
