### ISSUE TITLE
How do i go about adding non steam games with the theme installed?

### ISSUE THREAD

**Issue by grav3yardshawty** [tkashkin/Adwaita-for-Steam#240]

**Comment by tkashkin** [comment]
All default Steam menus are accessible by hovering the menu button.
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/2003017/35c5b116-9d77-45a4-91c3-cd1f306b3ea8)

There's also a button to add a non-Steam game in Settings > Library.
