### ISSUE TITLE
2nd layer buttons not accessible

### ISSUE THREAD

**Issue by Naezr** [tkashkin/Adwaita-for-Steam#241]
When I hover over the menu button, a second layer of buttons appears, but they cannot be clicked on because they disappear when the cursor is not over the menu button.

[Запись экрана от 2024-05-06 20-18-54.webm](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/87bfd964-e508-4f6b-83d1-a1727db5cf85)

**Comment by tkashkin** [comment]
Not much we can do with those menus, they are already quite buggy in an unmodified Steam client, and showing the buttons on hover probably doesn't help with this.

These buttons should stay visible when a menu is visible, so you should be able to click the last menu button and hover other buttons to open a different submenu.

**Comment by Naezr** [comment]
I figured out how to use those buttons. You have to click on menu button and when dropdown menu opens, you can move cursor over them and get its menus. I didn't really need those menus much, but the issue is now closed
