### ISSUE TITLE
Not all color themes are updated for v2

### ISSUE THREAD

**Issue by chomskysfavefive** [tkashkin/Adwaita-for-Steam#242]
Dracula theme does not apply. Everything about my hardware and software is the same as yesterday, the only thing that changed was that I updated AdwSteamGTK to 2.0. 

Steps to reproduce:
1. Exit Steam.
2. Install Dracula theme
3. Open Steam to a generic Adwaita theme without Dracula color palette. This is not expected behavior.

**Comment by chomskysfavefive** [comment]
The libraryroot css file shows that the Dracula theme is applied, but it's not. The colors.css seems like it's the generic Adwaita palette, not the Dracula palette.

**Comment by chomskysfavefive** [comment]
Also the web page part of the client is not themed at all. 

![Screenshot from 2024-05-08 00-39-05](https://github.com/tkashkin/Adwaita-for-Steam/assets/88474951/3f67e6e5-af26-444b-9e5d-9ff3e05cf559)

**Comment by Foldex** [comment]
Looks like most themes haven't been updated to the new format yet.
Aside from the below, the rest are going to be broken.

**Updated Themes**
[Adwaita](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/adwaita/adwaita.css)
[Breeze](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/breeze/breeze.css)
[Canta](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/canta/canta.css)
[Catppuccin-Frappe](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/catppuccin-frappe/catppuccin-frappe.css)
[Yaru](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/yaru/yaru.css)

**Comment by chomskysfavefive** [comment]
Copy that, thanks so much!

**Comment by chomskysfavefive** [comment]
Using the updated themes now as a demo. Fantastic work. The hover menus near the hamburger menu button are working great.

**Comment by eylles** [comment]
i cobbled a template for using with pywal on https://github.com/tkashkin/Adwaita-for-Steam/issues/205#issuecomment-1894783285 and i'm currently prototyping a python script to read a json file with colors from either pywal or gradience (that part of the script is already done) and was working on cobbling a template for the css for said script, if you would be so kind to direct me which is the correct css to use as template OR if the custom css is no longer going to be supported an example of how to add another color theme (if there is more to it than creating a directory under colorthemes with the right css)

**Comment by tkashkin** [comment]
@eylles 

> which is the correct css to use as template

Either [`adwaita/css/_root/colors.css`](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/css/_root/colors.css) or [`adwaita/colorthemes/adwaita/adwaita.css`](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/colorthemes/adwaita/adwaita.css), both are the same. They define all theme colors and mostly taken from the libadwaita stylesheet.
There are a few other variables defined in [`adwaita/css/_root`](https://github.com/tkashkin/Adwaita-for-Steam/tree/master/adwaita/css/_root).

> how to add another color theme (if there is more to it than creating a directory under colorthemes with the right css)

Create `adwaita/colorthemes/$name/$name.css` and it should be detected by the installer script.

**Comment by eylles** [comment]
@tkashkin  thanks for your input, hope to have it ready for the weekend.
