### ISSUE TITLE
Hover menus not rounded

### ISSUE THREAD

**Issue by shrek-gabe-itch** [tkashkin/Adwaita-for-Steam#243]
Platform: windows
Version: 2.0

![Screenshot 2024-05-08 214329](https://github.com/tkashkin/Adwaita-for-Steam/assets/58945139/92ff4678-68fb-4e28-aa97-ed0bf995097d)

**Comment by tkashkin** [comment]
These menus are separate windows that don't support transparency, at least on Linux.
There is a way to enable transparency, but it requires JS patches and leads to more issues. https://github.com/tkashkin/Adwaita-for-Steam/discussions/181#discussioncomment-6421005
