### ISSUE TITLE
Cannot create library.original.css backup file

### ISSUE THREAD

**Issue by shrek-gabe-itch** [tkashkin/Adwaita-for-Steam#245]
Platform: windows
Version: 2.0

If you update theme u can see this and nothing will work
need to delete the old library.original.css manually
![Screenshot 2024-05-08 200315](https://github.com/tkashkin/Adwaita-for-Steam/assets/58945139/51594ff7-f17d-415d-8e3c-0a932ffba0c8)

**Comment by tkashkin** [comment]
Should be fixed in [`v2.2`](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v2.2).
