### ISSUE TITLE
V2.0 broke custom css

### ISSUE THREAD

**Issue by shrek-gabe-itch** [tkashkin/Adwaita-for-Steam#246]
Platform: windows
Version: 2.0

Before update 2.0 I made myself custom window control buttons like this
![Screenshot 2024-05-08 201515](https://github.com/tkashkin/Adwaita-for-Steam/assets/58945139/a821c265-affd-4c1d-8396-0e871304a6e9)
after 2.0 in windows u need delete adwaita\css\widgets\windows.css to edit this styles

And custom css now only for variables, so what's the point of calling it custom.css?

**Comment by tkashkin** [comment]
Custom CSS still works as it did before, but Steam has completely changed most of CSS class names recently. You'll need to update selectors in your custom CSS.

**Comment by shrek-gabe-itch** [comment]
> Custom CSS still works as it did before, but Steam has completely changed most of CSS class names recently. You'll need to update selectors in your custom CSS.

I mean I cant customize windows title control buttons because of this file adwaita\css\widgets\windows.css
old selectos work fine
![Screenshot 2024-05-08 232340](https://github.com/tkashkin/Adwaita-for-Steam/assets/58945139/29a72265-6d49-44cf-81bc-2aafaa55a30a)

**Comment by shrek-gabe-itch** [comment]
> These particular classes are the same, but your CSS is probably not applied because of old selector having lower [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) than what's now used in the skin. Try updating selectors anyway: https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/extras/windowcontrols/right-all.css


everything worked out, thanks
looks a little bulky compared to what came before
```
body.DesktopUI .title-bar-actions .closeButton::before,
html.client_chat_frame .title-bar-actions .closeButton::before,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.minimizeButton::before,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.maximizeButton::before,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.restoreButton::before,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.closeButton::before {
	display: none !important;
}
.title-bar-actions {
	padding: 0 10px !important;
}
body.DesktopUI .title-bar-actions .title-area-icon,
html.client_chat_frame .title-bar-actions .title-area-icon {
	width: 15px !important;
	height: 15px !important;
	margin: 1px 0 0 18px !important;
	transition: all 0.3s ease !important;
}
body.DesktopUI .title-bar-actions .closeButton,
html.client_chat_frame .title-bar-actions .closeButton,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.closeButton {
	background: rgb(250, 55, 55) !important;
}
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.maximizeButton,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.restoreButton {
	background: rgb(252, 185, 15) !important;
}
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.minimizeButton {
	background: rgb(36, 209, 49) !important;
}
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.closeButton:hover,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.maximizeButton:hover,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.restoreButton:hover,
body.DesktopUI div._3Z7VQ1IMk4E3HsHvrkLNgo div.qP17eBPXkfezFfexZ4hC3 .title-area-icon.minimizeButton:hover {
	filter: brightness(50%);
}
```
