### ISSUE TITLE
chat and download page are not themed anymore 

### ISSUE THREAD

**Issue by Chrispycode** [tkashkin/Adwaita-for-Steam#247]
After updating, the chat has no theme applied, is this the  new css or did I mess something up?
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/22537998/a9a47015-c819-4df6-a481-02360f0f81ba)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/22537998/80adf0cd-57cf-487a-9cf0-1644f99a0dbb)

**Comment by tkashkin** [comment]
Yes, chat and some other dialogs are not themed yet in the current version.

I would probably keep the v2 branch separate for a while until some of these unstyled dialogs were complete if Valve didn't break CSS classnames in the middle of the v2 rewrite.

Now that these changes are in the stable Steam branch it's better to have a v2 release with what's already done (main window, library, settings (mostly)).

**Comment by katawajojo** [comment]
has there been any progress or update on this?

**Comment by tkashkin** [comment]
@katawajojo Chat window is in progress. Friends list should be done relatively soon.

![image](https://github.com/user-attachments/assets/dca5076c-d98b-464f-ad83-779861ff00d3)

**Comment by tkashkin** [comment]
Initial chat window styles are done in [v2.7](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v2.7).

**Comment by katawajojo** [comment]
oh this looks great! thank you so much :D

**Comment by Chrispycode** [comment]
It's looking great except with window controls left 
![Screenshot from 2024-11-06 00-35-50](https://github.com/user-attachments/assets/3eb29f01-2a31-48be-a63d-40a86aa1b092)

**Comment by tkashkin** [comment]
[v3.0](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v3.0) adds initial styles to Downloads page and fixes window controls.
