### ISSUE TITLE
dots windowcontrols disappear

### ISSUE THREAD

**Issue by MarsSwimmer** [tkashkin/Adwaita-for-Steam#248]
Im really appreciate this extension for steam, but in new version, dots style windowcontrols has gonne, and old dots style doesn't work for new steam client,

so, is it possible to update dots style work for new steam client?

best regard !

**Comment by tkashkin** [comment]
[v3.0](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v3.0) adds support for macOS and Windows-like window controls.
