### ISSUE TITLE
Many inconsistencies and minor bugs

### ISSUE THREAD

**Issue by Naezr** [tkashkin/Adwaita-for-Steam#250]
### Steam Flatpak installed on Fedora 40. Theme installed by AdwSteamGTK app

![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/dcc0c45e-6dc2-4de6-b5f9-75dd843737c5)

### Notifications toggles looks weird (Notifications tab)
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/5ad8a905-3b0f-41f3-a138-4a738761f8b5)

### Those buttons look out of place (Library tab)
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/33c8a00b-9a96-45d1-b2cc-7a01e3fb3704)

###  Those buttons are a little crooked (Controller tab)
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/ff47b7a0-3e40-47f5-a789-302f909194f9)

### The volume value is hidden under the slider (Music tab)
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/2da47c2e-78bb-48a3-abb9-4d582e1860c6)

### Updates tab slightly broken
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/97e08d22-2c24-4bda-ba9b-6f939c462919)

### Workshop tab looks out of place. Also, buttons overlapping text sometimes and popups appear somewhere in left.
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/d49caeb5-a318-4029-ab8b-36f5562d5ced)

### The overlay, and most of the windows in it, have either lost styling or are broken. Notifications have also lost style. Most likely one of Steam updates broke everything, notifications and overlay used to have Adwaita theme.
![изображение](https://github.com/tkashkin/Adwaita-for-Steam/assets/95460152/f35cfcfd-f3f1-4c9e-a47f-313b529327a3)

------------------------------------------------------

### This theme is great, I look forward to its continued development and improvement

**Comment by tkashkin** [comment]
Most of these are already fixed for some time. Open new separate issues if something is broken or unstyled.
