### ISSUE TITLE
Windows install path

### ISSUE THREAD

**Issue by Zetta1Reid0** [tkashkin/Adwaita-for-Steam#252]
Steam install path isn't hardcoded so I have to set it  manually in install.py every update , please add an option to batch file to set the target path.

**Comment by tkashkin** [comment]
[`v2.2`](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v2.2) should now read Steam install path from registry on Windows.
Also you should now be able to pass target path to `install.py` with #251 fixed.
