### ISSUE TITLE
windowcontrols/hide-close is missing buttons completely

### ISSUE THREAD

**Issue by pinbuck** [tkashkin/Adwaita-for-Steam#256]
![Screenshot_20240625_015218](https://github.com/tkashkin/Adwaita-for-Steam/assets/96911866/d5c6e458-c5ee-4a8b-817f-58a25b6e9866)
Expected: minimize, maximize, and close button apparent. A recent update on steam seemed to break it.
Omitting windowcontrols/hide-close leaves the X button there like normal.

**Comment by tkashkin** [comment]
`hide-close` is supposed to hide the close button. Other buttons are already hidden by default. The bug here is that it should also override the right margin.

Perhaps this extra should be called `hide-all` to make it more obvious.

**Comment by pinbuck** [comment]
ah oops, I realized my mistake. I was messing with the text in the document diagnosing steam skin breakage one day.
windowcontrols/right-all is what I had *intended* to put there.
