### ISSUE TITLE
Miss-aligned profile button/text for Steam Beta (1721173529)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [tkashkin/Adwaita-for-Steam#259]
![image](https://github.com/user-attachments/assets/949f6507-e0b3-432b-8bce-079a3cdae9da)
It should ideally be either dynamically moved to the left depending on your Steam username (as the long one I have) or have a certain limit of characters.
Even if it appears that the name display wasn't even taken in account in that setup, which may be the main issue, actually.
![image](https://github.com/user-attachments/assets/a47bdb89-427c-44b5-9009-b5fcfc20d239)
It appears differently when I hover/click the "hamburger"/overflow menu button.

**Comment by tkashkin** [comment]
Valve broke CSS class names again. 5dd28bd fixes some of the problems.
I'll wait for this beta to get pushed to the stable client branch before fixing smaller issues in case Valve changes anything else before that.
