### ISSUE TITLE
"None" option for window controls in theme doesnt work

### ISSUE THREAD

**Issue by Blisterexe** [tkashkin/Adwaita-for-Steam#260]
trying to get steam to fit in with my kde desktop.

this picture sums it up:
![image](https://github.com/user-attachments/assets/8eb0a65d-93c5-44f4-9ae3-a967e270a070)

**Comment by tkashkin** [comment]
Should work in [v3.0](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v3.0) with something like `--windowcontrols-layout :`
