### ISSUE TITLE
All pages other than the library appear blank

### ISSUE THREAD

**Issue by alba4k** [tkashkin/Adwaita-for-Steam#262]
Not sure if this is supposed to happen, for now at least

store, community and profile appear empty
![immagine](https://github.com/user-attachments/assets/fd4f6a03-6f14-4ac8-97b4-71ae40d263c4)

Installed using the graphical app

I still love this thing too much, so I will probably end up using it anyway and rather use the website for shopping etc

Disabling the "use GPU for webpage rendering" option fixes the issue. Still a workaround tho

**Comment by tkashkin** [comment]
I think it was a Steam bug, reopen if it still happens with the skin and doesn't happen without it.

**Comment by alba4k** [comment]
yeah it's working now, was probably temporary then
