### ISSUE TITLE
Corners are not rounded when enabled

### ISSUE THREAD

**Issue by ExposedCat** [tkashkin/Adwaita-for-Steam#268]
I did **not** enable "Disable rounded corners", but all window frames are still with full (not rounded) corners

**Comment by tkashkin** [comment]
There is no way to reliably round corners of all Steam windows and skin doesn't try to do that anymore.
"Disable rounded corners" option only affects corners of inner widgets.

You'll need to use some other way to force rounded window corners.
[Rounded Window Corners Reborn extension](https://github.com/flexagoon/rounded-window-corners) works for GNOME.
