### ISSUE TITLE
installation with patch fails

### ISSUE THREAD

**Issue by nanopone** [tkashkin/Adwaita-for-Steam#27]
installing with a patch fails to install because the script appears to be looking for a folder called "patch" instead of "patches". renaming "patches" to "patch" fixes this.

```
[rae@laptop Adwaita-for-Steam]$ ./install.py -p windowcontrols/left-all -w full
Copying to the stage directory /tmp/tmpg1gc1ys3/Adwaita

Applying patch windowcontrols/left-all...

Error applying patch: [Errno 2] No such file or directory: 'patch'
Installing skin Adwaita into /home/rae/.local/share/Steam/skins...
Directory /home/rae/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
[rae@laptop Adwaita-for-Steam]$ mv patches patch
[rae@laptop Adwaita-for-Steam]$ ./install.py -p windowcontrols/left-all -w full
Copying to the stage directory /tmp/tmpn1eo5jxk/Adwaita
Installing skin Adwaita into /home/rae/.local/share/Steam/skins...
Directory /home/rae/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
[rae@laptop Adwaita-for-Steam]$
```

**Comment by tkashkin** [comment]
No, your guess and solution are incorrect.

Installer expects the [`patch`](https://www.gnu.org/software/diffutils/manual/html_node/patch-Options.html) utility to be installed and that's what the error is about.
Renaming the patches folder just makes the installer unable to find any patches to apply, then the `patch` utility is not being called and there is no error.
