### ISSUE TITLE
"Something went wrong while displaying this content." appears on first launch (at boot).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [tkashkin/Adwaita-for-Steam#271]
**Errata**

1. > ![Screenshot_20240913_144127](https://github.com/user-attachments/assets/5602f0ee-4bec-4456-8ba3-9da7e87dbee4)
1. > ![Screenshot_20240913_144121](https://github.com/user-attachments/assets/77cc3a6b-cdae-4c24-81b6-71092921bbcf)

When I restarted Steam, that error had disappeared, but the theme had unapplied.

**Workaround**

Luckily, restarting Steam, then re-applying the theme temporarily remediates it until the next reboot.

**Environment**

1.	**`io.github.Foldex.AdwSteamGtk`**

	<blockQuote>
	
	```log
	PS /home/RokeJulianLockhart> flatpak info io.github.Foldex.AdwSteamGtk
	
	AdwSteamGtk - Give Steam the Adwaita treatment
	
	          ID: io.github.Foldex.AdwSteamGtk
	         Ref: app/io.github.Foldex.AdwSteamGtk/x86_64/stable
	        Arch: x86_64
	      Branch: stable
	     Version: 0.6.11
	     License: GPL-3.0-or-later
	      Origin: flathub
	  Collection: org.flathub.Stable
	Installation: system
	   Installed: 1.3 MB
	     Runtime: org.gnome.Platform/x86_64/46
	         Sdk: org.gnome.Sdk/x86_64/46
	
	      Commit: df858acb163a7269e0343ea9868d64ea72b4ee4f29b76066cac0b42021f48bc8
	      Parent: 70781e9ec97592890c9940f00c739ed45ed37ea0563f7f5e509508e49802a3aa
	     Subject: python3-packaging: Update packaging-24.0-py3-none-any.whl to 24.1 (dbdd4eff)
	        Date: 2024-07-27 02:49:55 +0000
	```
	
	</blockQuote>
	
1.	**`com.valvesoftware.Steam`**
	
	<blockQuote>
	
	```log
	PS /home/RokeJulianLockhart> flatpak info com.valvesoftware.Steam     
	
	Valve Corporation - Launcher for the Steam software distribution service
	
	          ID: com.valvesoftware.Steam
	         Ref: app/com.valvesoftware.Steam/x86_64/stable
	        Arch: x86_64
	      Branch: stable
	     Version: 1.0.0.79
	     License: LicenseRef-proprietary
	      Origin: flathub
	  Collection: org.flathub.Stable
	Installation: system
	   Installed: 45.5 MB
	     Runtime: org.freedesktop.Platform/x86_64/23.08
	         Sdk: org.freedesktop.Sdk/x86_64/23.08
	
	      Commit: 173cd565d98d4951bd858bad290e8481a9e72dbf5f7c9c980165a060666184b1
	      Parent: 98f034b154eed70b957bedcba0a5ce3785e70999b4aef85e1f6dd66f2eb15ff7
	     Subject: Add pressure-vessel's overrides data dir to XDG_DATA_DIRS (ee358536)
	        Date: 2024-04-03 13:45:40 +0000
	PS /home/RokeJulianLockhart>
	```

</blockQuote>

**(Lack of) Duplicates**

1. Originally posted at https://github.com/tkashkin/Adwaita-for-Steam/discussions/269#discussion-7178362 by myself.
1. https://github.com/tkashkin/Adwaita-for-Steam/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+Something+went+wrong+while+displaying+this+content returned 0 results at +2024-09-18T21:19:14+01:00.

**Comment by tkashkin** [comment]
Not a skin issue.

**Comment by RokeJulianLockhart** [comment]
@tkashkin, where might be better to report this?

**Comment by tkashkin** [comment]
There's probably already an issue somewhere there: https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by RokeJulianLockhart** [comment]
@tkashkin, the problem is that, from what I recall, it started after I applied the skin. I'd rather not report upstream a problem due to my client mods.

**Comment by tkashkin** [comment]
All I can say is that both issues should not be caused by the skin and should be reproducible on a clean Steam client install without any modifications.

**Comment by RokeJulianLockhart** [comment]
In retrospect, this appears to be an example of [`ValveSoftware/steam-for-linux/issues/12378`](https://github.com/ValveSoftware/steam-for-linux/issues/12378#issue-3514794465).
