### ISSUE TITLE
New steam update broke the theme

### ISSUE THREAD

**Issue by Stormtroppy** [tkashkin/Adwaita-for-Steam#276]
![steam](https://github.com/user-attachments/assets/35acbaeb-767c-4688-89a6-21478fc1efc0)
To the right of the window, the buttons from the default theme are there

**Comment by tkashkin** [comment]
Current theme version requires the latest Steam beta, see #274.
Switch to the beta client branch or roll back to [v2.6](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v2.6) for now.

I've marked v2.7 as pre-release and added a warning to its description. AdwSteamGtk also shouldn't pull v2.7 automatically now, though it may have done that already before it was marked as pre-release.

**Comment by Stormtroppy** [comment]
Switching to beta fixed it. Thanks for helping.
