### ISSUE TITLE
Incorrect profile picture and window actions display

### ISSUE THREAD

**Issue by Dzheremi2** [tkashkin/Adwaita-for-Steam#277]
![image](https://github.com/user-attachments/assets/0cd2b837-f393-4a6f-9ad3-ed67288d1c7c)
In this image, you can see that theme doesn't apply to profile picture and window buttons

**Comment by tkashkin** [comment]
Duplicate of #274, #276.

Current theme version requires the latest Steam beta.
Switch to the beta client branch or roll back to [v2.6](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v2.6) for now.
