### ISSUE TITLE
[BUG] can't click items in drop down menu in work shop for subscribed items

### ISSUE THREAD

**Issue by shadow-absorber** [tkashkin/Adwaita-for-Steam#278]
when clicking the dropdown browse tab in the workshop for any game does not work

**Comment by tkashkin** [comment]
Not sure which dropdown you're talking about. Can you attach a screenshot?

**Comment by shadow-absorber** [comment]
never mind... this is apparently a bug in steam itself on 4k/hdpi mode on linux: https://github.com/ValveSoftware/steam-for-linux/issues/9273
