### ISSUE TITLE
need arrows variables for macOS testing

### ISSUE THREAD

**Issue by luvingiane** [tkashkin/Adwaita-for-Steam#280]
Hey!
i tried to install adwaita on macOS and worked fine, however i noted that the macOS Buttons covers che arrow buttons.
i searched on the various files but i can't find the correct one (i'm learning css, i'm not an expert) 

can i ask you where to find them? with these, i can move buttons with a margin to resolve the issue. 

thanks a lot, sorry for silly question. 

<img width="345" alt="Screenshot 2024-11-05 alle 15 12 38" src="https://github.com/user-attachments/assets/a2831ed0-ec88-4a64-ac7c-604df63206fb">

**Comment by tkashkin** [comment]
There are a few variables [here](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/adwaita/css/_root/variables.css#L7-L13). [Windowcontrols extras](https://github.com/tkashkin/Adwaita-for-Steam/tree/master/adwaita/extras/windowcontrols) override them to move the buttons in the headerbar.

**Comment by luvingiane** [comment]
<img width="357" alt="Screenshot 2024-11-05 alle 16 18 16" src="https://github.com/user-attachments/assets/4fa97e18-5111-4296-b24b-9a8f43337f7c">
worked! however i've to admit that to achieve this result i had to edit the code. 

Thanks a lot for your help!
