### ISSUE TITLE
The ‘Window Control Buttons - Left’ option in AdwSteamGtk doesn't seem to work in 3.0

### ISSUE THREAD

**Issue by Naezr** [tkashkin/Adwaita-for-Steam#284]
I'm using the AdwSteamGtk app to install the theme. I launched it, saw the notification that version 3.0 was downloaded and installed it. Everything works, however the ‘Window Control Buttons’ option doesn't seem to affect anything

![image](https://github.com/user-attachments/assets/918844c3-43c6-48c3-b164-f9f14fc1ea13)

**Comment by tkashkin** [comment]
v3.0 changes how window controls work.
AdwSteamGtk should support new options in the next release - https://github.com/Foldex/AdwSteamGtk/issues/66.
