### ISSUE TITLE
Minimize and close window control layout

### ISSUE THREAD

**Issue by seadx6-neo** [tkashkin/Adwaita-for-Steam#293]
Hi there Adwaita for Steam devs, could you add the minimize and close on the right button layout to the skin? although I love the default GNOME way of doing things I am a fervent lover of the vanilla plus conept, I usually use Dash to dock + Blur my shell + minimize button to get the most complete version of the vanilla UX while still having nice things

![Screenshot From 2024-12-22 07-46-41](https://github.com/user-attachments/assets/d8242a8e-35d7-4d3c-ba6e-3524bf49d9b1)
Could this be done?

**Comment by tkashkin** [comment]
How are you installing the skin and are you using the latest version?

Adwaita for Steam v3.0 or later supports custom button layouts and should read your current layout from system settings by default.
If installer can't read your layout for some reason, use `--windowcontrols-layout :minimize,close` option to get the layout you want.

If you're using AdwSteamGtk, it should also support new layout options and it should read your system settings, but I don't think it exposes an option to use a custom layout.

**Comment by seadx6-neo** [comment]
Thanks, it even worls on AdwSteamGtk if you allow it to access user configs on Flatseal, I suggest you adding a small explanation on your read me or flathub page

**Comment by tkashkin** [comment]
AdwSteamGtk should also read settings using the desktop portal. Looks like a bug, report it to AdwSteamGtk if it doesn't work or requires additional permissions on your system.

**Comment by seadx6-neo** [comment]
Not a bug, what I meant is... You said

> If you're using AdwSteamGtk, it should also support new layout options and it should read your system settings, but I don't think it exposes an option to use a custom layout.

I was only telling you it does and it is exposed as auto, I just exposed the settings via Flatseal

**Comment by tkashkin** [comment]
AdwSteamGtk should read settings through the portal without having to expose anything manually and without any additional permissions. If it can't read settings after installing it's probably still a bug.
