### ISSUE TITLE
Settings sidebar selection alignment issue

### ISSUE THREAD

**Issue by arshubham** [tkashkin/Adwaita-for-Steam#31]
The selection in the side bar has misaligned edges.  Using Steam on Gnome Wayland 43.0 (Arch). 

![image](https://user-images.githubusercontent.com/14235191/193893786-20754630-f6f3-4f57-a55f-0e138778a066.png)

![image](https://user-images.githubusercontent.com/14235191/193893848-74e0e423-47eb-4b8f-8be6-e4bd340b8dba.png)

**Comment by tkashkin** [comment]
Looks like you're using a different font, do you have `Cantarell` font installed?

**Comment by arshubham** [comment]
Yes. Can I set the fonts just for steam or do I have to change the system fonts?
![image](https://user-images.githubusercontent.com/14235191/194220949-34e79019-772e-46f1-9c3c-1317f0027476.png)

**Comment by tkashkin** [comment]
System fonts should not matter but for some reason your Steam client uses a different font.

Are you using a native Steam package or the flatpak?
Try resetting the font cache or see if [ArchWiki](https://wiki.archlinux.org/title/Font_configuration) has other solutions.

**Comment by tkashkin** [comment]
This issue is probably related to #45, try installing static versions of Cantarell fonts.

**Comment by arshubham** [comment]
@tkashkin Using the static fonts fixes the issue for me. Thanks.
