### ISSUE TITLE
Cannot limit bandwith.

### ISSUE THREAD

**Issue by LethalManBoob** [tkashkin/Adwaita-for-Steam#36]
Apply button does not work.

**Comment by tkashkin** [comment]
Seems to work for me. Make sure you are saving settings with OK button and not just closing the dialog with Cancel or Escape.

**Comment by LethalManBoob** [comment]
Ahh i see the issue. Before it would apply instantly when clicking apply but now i also have to click ok. Maybe that should be addressed? but its a non issue now.
