### ISSUE TITLE
Store drop-down view is slightly larger than the others.

### ISSUE THREAD

**Issue by AndrejSh3** [tkashkin/Adwaita-for-Steam#46]
The drop-down menu for the Store tab is larger than the tab size itself.
![image](https://user-images.githubusercontent.com/61660699/196031351-75b34ec2-0490-4672-9e47-a8fc7d713f6b.png)
As far as I can tell, all of the other tabs fit the tab size well, like so:
![image](https://user-images.githubusercontent.com/61660699/196031396-f09a81df-bdd0-4e30-88da-5ab27f50363e.png)
![image](https://user-images.githubusercontent.com/61660699/196031408-82f86093-8d80-4787-9ecd-a7942e3a5985.png)
![image](https://user-images.githubusercontent.com/61660699/196031415-870b1de1-37cb-4218-8c94-ff1990b963e7.png)
Running fedora silverblue 36, steam is installed as flatpak, and the theme was manually installed (current version 0.16)

**Comment by tkashkin** [comment]
That's not really a problem, it just happens that in English localization only "Discovery Queue" string is long enough to make the menu wider.
Other languages have longer strings in different menus and therefore different menus will be wider, this is not a problem with the Store menu in particular.
