### ISSUE TITLE
Can't scroll in settings window

### ISSUE THREAD

**Issue by forteller** [tkashkin/Adwaita-for-Steam#49]
Hey, great theme!

Just wanted to let you know that when going to some place in the settnigs window where there's a scroll bare, like in "Interface" or "In-Game", using the scroll wheel on the mouse does nothing. 

Thanks! :)

**Comment by tkashkin** [comment]
This is a known issue and I doubt there's any way to fix it. You can scroll by dragging the scrollbar but not with the scroll wheel.

This is just how scrollable regions in VGUI work.
I guess this is also the reason why Steam skins generally don't try to do something like that and don't deviate from the default layout too much.

So I see four potential solutions:
1. Keep it as is and don't do anything.
2. Increase the height of the Settings dialog. That would look weird and may not fit on small screens.
3. Change the layout of the larger Settings pages to something like columns or remove some less useful controls. That would also look weird.
4. Same as #45:
> You can report this to Valve in their [issue tracker](https://github.com/ValveSoftware/steam-for-linux) but the chance of them fixing this is probably somewhere around 0%.

Option 1 seems the best, there are only a few places affected by this issue and none of them are critical.
