### ISSUE TITLE
Drop-down menu is truncated

### ISSUE THREAD

**Issue by RochaLAJ** [tkashkin/Adwaita-for-Steam#50]
**Evidence**
![image](https://user-images.githubusercontent.com/43121804/196313704-1fc0f7d2-68ae-4639-ac29-464390626b29.png)

That is the only one where i noticed such behavior.  Originally, 'Account det...' (account details) would be on a different line and would not be truncated, while 'Log out of ac...' (log out of account) is the last item of this menu.

Setup:
GNOME 43
Arch Linux x64

**Comment by cewbdex** [comment]
Mine is broken entirely:
![obrazek](https://user-images.githubusercontent.com/9021297/229211368-5a4b20f8-9653-4366-a076-c38cdab66db1.png)
