### ISSUE TITLE
Friendlist own avatar frame is misaligned

### ISSUE THREAD

**Issue by SnoutBug** [tkashkin/Adwaita-for-Steam#53]
In this image you can see that the profile picture is not centered in the avatar frame
![image](https://user-images.githubusercontent.com/71790678/196486836-f046bb16-9635-41f7-86cd-a00515e5762e.png)

**Comment by Eschguy** [comment]
Confirming this issue persists
![Screenshot from 2022-12-12 11-48-24](https://user-images.githubusercontent.com/8880292/207117205-11af4945-2906-4f2f-a202-2de195b350bd.png)
