### ISSUE TITLE
Web content not respecting windowcontrols patches

### ISSUE THREAD

**Issue by Willdrick** [tkashkin/Adwaita-for-Steam#56]
I used `./install.py --patch windowcontrols/left -w full` and the web-based UI (friends list, chat windows) still have the window controls on the right. Is this PEBKAC or is not yet implemented?

**Comment by Foldex** [comment]
Not yet implemented.
CSS can obviously do it, but getting every page with a window control properly formatted might not involve the prettiest of solutions and be prone to getting broken down the line by some minor change on Valve's end.

**Comment by Foldex** [comment]
@tkashkin This and https://github.com/tkashkin/Adwaita-for-Steam/issues/84 https://github.com/tkashkin/Adwaita-for-Steam/issues/85 were addressed in https://github.com/tkashkin/Adwaita-for-Steam/pull/111
Can probably close em.
