### ISSUE TITLE
Longer profile names get truncated

### ISSUE THREAD

**Issue by Unaccounted4** [tkashkin/Adwaita-for-Steam#59]
Is there an option to embiggen the profile name header button so it doesn't clip the username? Even if it's not introduced by default, if you let me know which file/entry to edit, I'll figure it out for myself.

![screenshot](https://user-images.githubusercontent.com/45717994/196561999-94bf3cbc-667d-412e-8d6e-e89c013d80a2.png)

**Comment by Foldex** [comment]
See https://github.com/tkashkin/Adwaita-for-Steam/issues/16#issuecomment-1236081547

**Comment by Unaccounted4** [comment]
Perfect, thanks

![picture](https://user-images.githubusercontent.com/45717994/196564666-9b043dd7-bed8-4e8f-a7cc-749421d74019.png)
