### ISSUE TITLE
Self Updater - text misaligned

### ISSUE THREAD

**Issue by derenv** [tkashkin/Adwaita-for-Steam#63]
The "A Steam client update has been downloaded." text in the self-updater notification pop-up isn't displaying properly - some kind of misalignment?

See below:
![Screenshot_20221019_203030](https://user-images.githubusercontent.com/35734401/196786330-3b7f920f-2a11-430c-b104-516ffc655f37.png)

Some examples of normal version (from google, it updated when i restarted to see the normal version, duh):
![image](https://user-images.githubusercontent.com/35734401/196787042-5c826785-8064-446d-bd4e-7b5f6a60d2ce.png)
![image](https://user-images.githubusercontent.com/35734401/196787065-9a40d895-9c9e-47c3-b63f-933c1a9e2224.png)

**Comment by forteller** [comment]
It's the same while the update is downloading: 

![image](https://user-images.githubusercontent.com/343561/198721700-f046527b-69a8-4a62-8540-43210886d476.png)
