### ISSUE TITLE
[Feature request] Make "new to library" partially rounded too

### ISSUE THREAD

**Issue by Midou36O** [tkashkin/Adwaita-for-Steam#66]
![image](https://user-images.githubusercontent.com/45198486/196939330-d1c44dae-9c02-4d33-a4ab-d0d84b943737.png)
The "new to library" feels off when its two corners at the bottom aren't rounded (and aligned with the top of the cover)

**Comment by SnoutBug** [comment]
Perhaps it would be an idea to stretch this element across the entire width of the game cover like a banner?

**Comment by Midou36O** [comment]
Like a sealed box?

**Comment by Foldex** [comment]
![ss-2022-10-20_21:02:31](https://user-images.githubusercontent.com/47908676/197087703-0f2e08dd-57f4-4cc0-86af-0c6ce6679e06.png) ![ss-2022-10-20_21:00:53](https://user-images.githubusercontent.com/47908676/197087705-4b6cfecd-f3cf-4494-a6cf-ee1a29f13c19.png)

Could go for either, honestly.

**Comment by SnoutBug** [comment]
> Could go for either, honestly.

Yes, i agree unfortunately

**Comment by Midou36O** [comment]
I prefer the second one imo, it looks like the gnome software software information pop up
![image](https://user-images.githubusercontent.com/45198486/197186567-8194540c-e590-4a56-b511-5a3523938bee.png)
