### ISSUE TITLE
Small mode support

### ISSUE THREAD

**Issue by aaaa2aaaa** [tkashkin/Adwaita-for-Steam#69]
Hello, I saw in the README that you'd be willing to add small mode support if requested. I use steam with `-no-browser` so small mode is the only view that works. I would greatly appreciate it if you added support for this.

Sorry for my English it is my second language

**Comment by tkashkin** [comment]
Latest release adds small mode support. Let me know if something is broken or missing.

**Comment by aaaa2aaaa** [comment]
Works extremely well even with `-no-browser` which normally breaks a bunch of stuff since steam keeps replacing the UI with CEF, thank you so much!
