### ISSUE TITLE
Family View Toggle

### ISSUE THREAD

**Issue by Croplight** [tkashkin/Adwaita-for-Steam#7]
Needs a toggle for Family View somewhere on the interface or in one of the drop-down menus. Depending on how people have set up Family View, accessing the Store or the Settings menu might be impossible without the button. Style in stock Steam client:

![Screenshot from 2022-08-07 19-07-39](https://user-images.githubusercontent.com/24968481/183316520-e84b7c51-04f8-43e9-9db1-43e7cc7d653e.png)

**Comment by tkashkin** [comment]
Would something like this be noticeable and clear enough or should the whole icon be colored?

![image](https://user-images.githubusercontent.com/2003017/183322849-4a8e56ad-41dc-49a7-b66e-a312a179ffc8.png)

**Comment by Croplight** [comment]
I think the partial-colored icon looks good, more subtle. Either the locked or unlocked icon can be uncolored if you think it might look better, probably the locked icon since it's on-screen more.
