### ISSUE TITLE
Overlay: settings button overlap

### ISSUE THREAD

**Issue by ChaosMelone9** [tkashkin/Adwaita-for-Steam#70]
Selecting settings in the overlay looks like this:
![grafik](https://user-images.githubusercontent.com/59118042/198530759-0e01d73e-16c8-48ba-8603-048914d06410.png)
It possibly should look like the regular settings:
![grafik](https://user-images.githubusercontent.com/59118042/198530987-672bfa56-a06f-49f6-a870-9ff64b0bf435.png)

Anyways, thank you for the work you are doing!

**Comment by tkashkin** [comment]
Doesn't seem to be possible to hide the close button without also hiding it in the other windows where it's needed. The best I could do is keep both buttons and move the OK button a bit.

OK button will save the changes and close button will discard them.
