### ISSUE TITLE
The uninstall game prompt is duplicated and UI gets zoomed

### ISSUE THREAD

**Issue by alosarjos** [tkashkin/Adwaita-for-Steam#73]
When trying to uninstall a game, the dialog to confirm shows the native and the theme version. Also for some reason the UI gets ZOOMED

Before trying to uninstall:

![Captura desde 2022-11-01 16-19-46](https://user-images.githubusercontent.com/29999427/199269586-ddf967a4-e956-40c1-8e38-1addf14f9aa8.png)

After clicking uninstall:

![Captura desde 2022-11-01 16-19-55](https://user-images.githubusercontent.com/29999427/199269645-ccd91a46-9566-4823-bc9d-de1f999e88b5.png)

**Comment by alosarjos** [comment]
Same thing happening with default theme. My bad...

**Comment by tkashkin** [comment]
Should be (mostly) fixed in the [latest Steam beta](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3388422948432807440):

> Fixed issue where uninstall dialogs were showing up twice (this may still happen after bringing up the controller configurator or standalone keyboard).

Scaling also seems to be a new beta bug, not mentioned in the patchnotes yet.

**Comment by alosarjos** [comment]
The scaling seems to be fixed with todays beta release too
