### ISSUE TITLE
Steam "Update News" chrome pops up separately from content

### ISSUE THREAD

**Issue by Vash63** [tkashkin/Adwaita-for-Steam#74]
The 'Update News'  dialogue comes up as two separate windows, one with the chrome and the other with content (see screenshot)

![Screenshot from 2022-11-13 17-50-45](https://user-images.githubusercontent.com/3086017/201534919-66ff8a53-8a25-4a91-82b1-b58e57dcaa7b.png)

**Comment by tkashkin** [comment]
That's another Steam beta bug, happens with the default skin as well.
