### ISSUE TITLE
Weird new font issue

### ISSUE THREAD

**Issue by rowbawts** [tkashkin/Adwaita-for-Steam#75]
So this issue is new as the fonts were working properly before on the same system. You can see the text in the menubar is too large.

![image](https://user-images.githubusercontent.com/13012832/201588985-6f2ca106-242a-44fe-83f3-146d93a28786.png)

Before

![Screenshot from 2022-08-06 19-20-33](https://user-images.githubusercontent.com/13012832/201589131-af3d8cfe-ac97-46bc-b42c-07aa76c74cdf.png)

**Comment by tkashkin** [comment]
I haven't done any changes to fonts recently. Does the Settings dialog also have weird fonts or does it look normal?

It may be the same issue as #45, make sure you have the normal (non-variable) version of Cantarell font installed.
It may also just be a Steam bug, a few latest Steam betas have some issues with scaling.

**Comment by rowbawts** [comment]
I do, but I'm actually investigating this issue and it seems to not be the skin causing it, so I will close for now and re-open when its conclusive that your skin is the issue (not likely)
