### ISSUE TITLE
Add alternate skin directory ~/.steam/steam/skins

### ISSUE THREAD

**Issue by ZechariahB** [tkashkin/Adwaita-for-Steam#8]
The directory `~/.local/share/Steam/skins` has been suggested as the place to install skins by every web article imaginable and the truth is it may not be good enough information.

At least with Ubuntu 22.04 with Steam installed though apt, any theme placed there results in no theme found by Steam. A package maintainer caused issue I presume?? A directory that does work is located at `~/.steam/steam/skins` courtesy of a comment within [Skins not detected #5079 ](https://github.com/ValveSoftware/steam-for-linux/issues/5079)

**Comment by tkashkin** [comment]
On Fedora `.steam/steam` is a symlink for `.local/share/Steam` for both the regular package and the flatpak:

```
$ readlink ~/.steam/steam ~/.var/app/com.valvesoftware.Steam/.steam/steam
/home/tk/.local/share/Steam
/home/tk/.var/app/com.valvesoftware.Steam/.local/share/Steam
```

Is it different on Ubuntu? Did you install Steam package from Ubuntu repos or `steam.deb` from https://store.steampowered.com/about?

**Comment by ZechariahB** [comment]
It appears the symlink is different for Ubuntu, unfortunately. The installer script may need to be edited to accommodate for this.
```
$ readlink ~/.steam/steam
/home/user/.steam/debian-installation
```

Steam was installed from the default repo set for Ubuntu (Jammy Jellyfish). The .deb file from steam website was not tested. I do not know whether the symlinks are different for it.

**Comment by tkashkin** [comment]
Does `./install.py -d ~/.steam/steam` work?

**Comment by ZechariahB** [comment]
`./install.py -d ~/.steam/steam` works without issue. It might be confusing to people who do not know about the directory, installed the skin, and found out that they are not listed. A good simple fix to this is to edit the README file to list the extra path in the Manual Installation section. The installer could also be added an option of using either path for convenience. Other than that, this seems to be flowers and meadows.
