### ISSUE TITLE
Steam's hidden library

### ISSUE THREAD

**Issue by afm0901x** [tkashkin/Adwaita-for-Steam#82]
Is there a way to access hidden game/software?

I accidently hide my favourite game :(

As for workaround right now, I switched to the default theme, unhide the game, and switch back to Adwaita.
A proper fix would be an entry in sandwich menu.

**Comment by andrew1412** [comment]
If you search the game/program by name it shows in a sub menu.

**Comment by tkashkin** [comment]
The menu already has a lot of items and "Hidden games" doesn't seem important enough to be there.

There are a couple of other ways to access hidden games:
* Search shows hidden games in a separate category.
If you know the game's name, search for it and unhide it.
* Open `steam://nav/library/collection/hidden` in a browser or with `xdg-open`.
`steam steam://nav/library/collection/hidden` should also work.

If you want to add it to the menu, edit [`Adwaita/resource/menus/steam.menu`](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/menus/steam.menu) and add this entry somewhere:

```
Hidden { text="#steam_menu_hidden_games" shellcmd="steam://nav/library/collection/hidden" }
```
