### ISSUE TITLE
Tooltips on activity page display in wrong position

### ISSUE THREAD

**Issue by Rayquaza01** [tkashkin/Adwaita-for-Steam#83]
On the Activity page, the tooltips that appear when hovering over an achievement are positioned incorrectly.
If the window is maximized, the tooltip appears in the upper left corner of the window. If the window is restored down, the tooltip appears in the bottom left of the window.

Maximized:
![Issue maximized](https://user-images.githubusercontent.com/22138871/206869482-5b780cbe-333c-4940-b225-6561d32c74df.png)
Restored:
![Issue restored](https://user-images.githubusercontent.com/22138871/206869484-dc221a6e-05a1-4193-b52e-a753d481dd16.png)

My OS is Fedora 37, GNOME 43.

**Comment by tkashkin** [comment]
Tooltips should behave the same way with the default (or any other) skin. Skins can't control tooltip sizes and positions.

That's another Steam bug, nothing to fix here.

**Comment by Rayquaza01** [comment]
Does it appear like that only if a custom skin is applied? Tooltips appear in the right place if I switch to the default skin.
![Screenshot from 2022-12-10 14-38-06-obfuscated](https://user-images.githubusercontent.com/22138871/206872549-f7168878-bbb2-47eb-9219-377149d74254.png)

**Comment by tkashkin** [comment]
Should be fixed in 4ad8301. I forgot about `Tooltip.Anchor` property.
