### ISSUE TITLE
Titlebars For Popup Windows Limited In Function

### ISSUE THREAD

**Issue by cprin21** [tkashkin/Adwaita-for-Steam#84]
With the full titlebar buttons option via AdwSteamGtk, opening the Friends List and Chat popup windows shows that there is no way to minimize these windows, despite being able to do so on the default Steam skin. Below you can see - the chat on the left should have, with the full button option, a maximize and minimize button, while the Friend List on the right should have a minimize button.

![Screenshot from 2022-12-10 21-28-22](https://user-images.githubusercontent.com/107228497/206883689-8ed9e168-83b5-4087-9918-cd6e0eaaadf4.png)

**Comment by Foldex** [comment]
![ss-2022-12-27_20:02:00](https://user-images.githubusercontent.com/47908676/209741734-987e3d88-0b75-40c3-bd7a-3548ee797f1f.png)
The default is to not show them per gnome defaults, but at least with the right-all window patches this shouldn't be the case on an up-to-date release.
Left aligned window controls for web content have yet to be implemented, see https://github.com/tkashkin/Adwaita-for-Steam/pull/67

**Comment by cprin21** [comment]
I suppose it would be a feature request then and not a bug report for both left and right aligned titlebar buttons that include maximize and minimize buttons as set by gnome-tweaks as an option.
