### ISSUE TITLE
Community tab gets truncated when translated to brazilian portuguese as "Comunidade"

### ISSUE THREAD

**Issue by fabriciojardim** [tkashkin/Adwaita-for-Steam#86]
This is similar to #16 and #59, but for me is the "Community" tab that gets truncated when translated to brazilian portuguese as "Comunidade". 

![Captura de tela de 2022-12-15 20-17-49](https://user-images.githubusercontent.com/29047175/207988711-a5a17459-24f0-45f6-b0b6-ea2f2a7fe015.png)

I'm aware of the rationale and the workaround as mentioned on #16. I wonder if some compromise might be considered by default to avoid those issues.

**Comment by tkashkin** [comment]
Similarly to #92 fonts on your screenshot look bolder than they should be.
These labels are short enough to fit with the correct font.

Check if you have non-variable Cantarell fonts installed, see #45.

**Comment by fabriciojardim** [comment]
> Similarly to #92 fonts on your screenshot look bolder than they should be. These labels are short enough to fit with the correct font.
> 
> Check if you have non-variable Cantarell fonts installed, see #45.

I have default Fedora 37 fonts. They do not mention "variable" in the name.

Will try to reproduce with non- flatpak steam latter.
