### ISSUE TITLE
"Library" button is not showing fully

### ISSUE THREAD

**Issue by Vitalya-code** [tkashkin/Adwaita-for-Steam#92]
In ukrainian localization of steam "Library" button is not showing fully. I don't know is it bug or not.
 

![Screenshot from 2023-01-04 22-21-22](https://user-images.githubusercontent.com/58048618/210643907-34d5c5db-4a82-4e5e-9f94-4b108bbc8a8f.png)

**Comment by tkashkin** [comment]
Your client seems to use wrong fonts, that's probably the same issue as #45. Make sure you have non-variable Cantarell fonts installed.

It should fit with a correct font:

![image](https://user-images.githubusercontent.com/2003017/210766733-6ee37d9b-d828-484b-afcc-7f15290e3dab.png)
