### ISSUE TITLE
Top bar broken after latest beta update

### ISSUE THREAD

**Issue by alosarjos** [tkashkin/Adwaita-for-Steam#93]
Can't either click on the icons so can't navigate to the library

![imagen](https://user-images.githubusercontent.com/29999427/210959748-5970ced1-679e-438a-ad70-373a35a579ac.png)

**Comment by KibaGasteiz** [comment]
More info:
![Captura desde 2023-01-06 13-13-09](https://user-images.githubusercontent.com/44957566/211011036-30e8c3fe-5fd7-4e40-941c-7c87acd1249c.png)
![Captura desde 2023-01-06 13-14-22](https://user-images.githubusercontent.com/44957566/211011043-5b1c8fd8-d158-4c07-9d8c-679278284c9b.png)

**Comment by alosarjos** [comment]
I can confirm, with latest changes, it's fixed. Thanks a lot :D

**Comment by tkashkin** [comment]
Should be fixed in 799fdd7.

There are also changes in Downloads settings, this will require more work and will be fixed later.
Seems like Valve is preparing to roll out peer-to-peer downloads.
